version: "3.0"
services:

  wsc_app:
    build: .
    environment:
      - DEV_MODE=true
      - POSTGRES__SERVER_NAME=wsc_postgres
      - POSTGRES__PORT_NUMBER=5432
      - LANGCHAIN__EMBEDDING_MODEL__URL=http://wsc_ollama:11434
    volumes:
      - ./target/inbound:/usr/src/app/target/inbound
    depends_on:
      - wsc_postgres
    networks:
      - wsc
    ports:
      - "8080:8080"

  wsc_postgres:
    image: "ankane/pgvector:latest"
    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all -c log_statement=all
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - wsc_postgres_data:/var/lib/postgresql/data
    networks:
      - wsc
    ports:
      - "15457:5432"

  wsc_ollama:
    image: "ollama/ollama:latest"
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - wsc_ollama_data:/root/.ollama
    networks:
      - wsc
    ports:
      - "11434:11434"

  wsc_ollama_init:
    image: curlimages/curl:latest
    depends_on:
      - wsc_ollama
    entrypoint: /bin/sh -c
    command: >
      "
        curl -X POST http://wsc_ollama:11434/api/pull -d '{\"name\": \"llama3.1\"}'
      "
    networks:
      - wsc

volumes:
  wsc_postgres_data:
  wsc_ollama_data:

networks:
  wsc:
    driver: bridge
